### ISSUE TITLE
Inspecting an object should not fire .get on all its CPs

### ISSUE THREAD

**Issue by machty** [emberjs/ember-inspector#167] opened 2014-05-29 23:44 UTC
Clicking an object to inspect it in Ember inspector shouldn't run .get() on all of its CPs, since in some cases where you're debugging lazy CP bugs and other issues, Ember Inspector will put you into Heisenbug land if you're trying to figure out why a computed property hasn't been calculated/invalidated.

I propose we offer similar behavior to how Chrome inspector doesn't eagerly computed getter properties, but forces you to click the property value to calculate it:

![clicking properties evaluates getter](http://recordit.co/uHv9lmkJSB.gif)

But for CPs we should display a cached value for CPs that have already been computed, and allow you at any time to click the calculator icon to explicitly call .get() on it.

/cc @hjdivad

**Comment by Bestra** [comment] 2018-10-01 17:13
@rwwagner90 I think the issue is more that showing a property in the inspector will cause that computed property to recalculate/be evaluated/whatever you want to call it.  I don't think the syntax change had an effect on the root of this issue.  I bet we've all run into the problems that Alex brings up (I've totally had the exact problems he mentions in his final comment) but I think it's worth closing this for the time being.

**Comment by rwwagner90** [comment] 2018-10-01 19:13
Closing as wontfix for now. After reading through this more thoroughly, I tend to agree that we should not be trying to support all the things here. I think for normal day to day inspection, it is nice to see the property values already, without extra clicks.

**Closed by rwwagner90** 2018-10-01 19:13 UTC
Labels: wontfix
