### ISSUE TITLE
Selecting a component dos not open the sidebar

### ISSUE THREAD

**Issue by TSenter** [emberjs/ember-inspector#1820] opened 2021-11-29 16:00 UTC
**Describe the bug**
When I select a component or route from the "Components" menu, nothing is selected and a warning is thrown in the console.

**To Reproduce**
1. Open an Ember app
2. Open the Ember Inspector
3. Go to the "Components"
4. Select any component or route
5. See error in console

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7104823/143898902-49faa479-c482-4461-9951-66a56c3aee59.png)

**Environment**
- ember-cli `v3.26.1`
- Node.js `v14.17.3`
- Microsoft Edge: `Version 96.0.1054.29 (Official build) (64-bit)`
- Ember Inspector: `v4.5.3`
- Windows 10 `v10.0.19043 Build 19043`

**Additional context**
Not necessarily context but I have not had this problem until recently. I used Chrome and this problem was constant there, but switched to Edge and never had this issue until recently.

**Comment by rwwagner90** [comment] 2021-11-30 15:22
@TSenter is this a template only component perhaps?

**Comment by rwwagner90** [comment] 2021-11-30 15:23
Oh wait, just saw the screenshot duplicate of #1812

**Closed by rwwagner90** 2021-11-30 15:23 UTC
Labels: bug
