### ISSUE TITLE
Dynamic models are not visible

### ISSUE THREAD

**Issue by SeyZ** [emberjs/ember-inspector#409] opened 2015-06-26 13:50 UTC
In my Ember application, I register dynamic models. Example:
    
    this.container._registry.register('model:foo', { ... });

The problem is dynamic models are not visible in the Ember inspector (data tab).
Is there a possibility to refresh the list of available models?

**Comment by teddyzeenny** [comment] 2015-06-26 14:01
Duplicate of https://github.com/emberjs/ember-inspector/issues/285

**Closed by teddyzeenny** 2015-06-26 14:01 UTC
