### ISSUE TITLE
Ember Inspector is hanging up on Ember 2.8.0 app

### ISSUE THREAD

**Issue by calmwater** [emberjs/ember-inspector#593] opened 2016-09-14 18:14 UTC
I recently upgraded my app from 2.4.x to 2.8.0 and the Google Ember Inspector just hangs up and doesn't show anything other than the left side menu. It also doesn't respond to clicking on anything?? The app works great in test and production modes with no deprecation warnings. A real mystery. Chrome version 53.0.2785.113, Ember Inspector 2.0.2. Interesting that the Firefox version works fine, Firefox version 48.0.2, Ember Inspector 2.0.1.

**Comment by teddyzeenny** [comment] 2016-09-14 18:47
Probably duplicate of https://github.com/emberjs/ember-inspector/issues/585

**Closed** 2016-09-14 19:51 UTC
