### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'map' of undefined"

### ISSUE THREAD

**Issue by lolmaus** [emberjs/ember-inspector#314] opened 2015-02-13 11:31 UTC
[This line](https://github.com/emberjs/ember-inspector/blob/eec4f25b3fd3b9c3a4db414525d7c63507f4bdc8/ember_debug/container-debug.js#L73) produces an error: 

> Uncaught TypeError: Cannot read property 'map' of undefined

The inspector remains in "Ember application not detected!" state.

**Comment by teddyzeenny** [comment] 2015-02-13 11:50
Thanks for reporting this. Can you post what versions you are using?

**Comment by lolmaus** [comment] 2015-02-13 12:06
* Ember Inspector 1.7.2
* Ember 1.9.1
* Ember Data 1.0.0-beta.14.1
* Handlebars 2.0.0
* jQuery 1.11.2
* Ember Simple Auth 0.7.3
* Ember Simple Auth Cookie Store 0.7.3

**Comment by lolmaus** [comment] 2015-02-13 12:06
The problem doesn't happen all the time. It only happens on my app's login page.

**Comment by teddyzeenny** [comment] 2015-02-13 12:24
I think I know what the issue is, let me know if this is it. You open the container tab, and select a specific type. Then you reload. What happens is that we request that type's instances on page load, before any instance of that type is looked up yet and the container has nothing cached for this type.

So if you don't have the container tab open and that type selected before you reload, the inspector should work.

**Comment by lolmaus** [comment] 2015-02-13 12:27
Uhm... I did fiddle with the Container tab before i caught the error, so you must be right.

But i can't reproduce it. No error so far even when i select an item in the Container tab and reload.

**Comment by teddyzeenny** [comment] 2015-02-13 12:36
It depends on which type you pick. I think it needs to be a type that you don't lookup on app boot.

**Comment by jacobthemyth** [comment] 2015-03-12 00:16
I was able to reproduce this error another way too:

1) Register and inject a new type in an initializer

```js
application.register('cool:thing', Ember.Object);
application.inject('route', 'thing', 'cool:thing');
```

2) Select that type in the container tab
    ![screen shot 2015-03-11 at 8 10 51 pm](https://cloud.githubusercontent.com/assets/1620230/6609702/617c7708-c82b-11e4-812c-b88fe0c614ef.png)

3) Delete the register and inject lines

**Comment by j-mcnally** [comment] 2015-03-19 16:54
OMFG

**Comment by geoffreyd** [comment] 2015-03-27 00:19
Another more common case for this to popup, which I've been hitting recently, is with helpers, if you're app has helpers, visiting a route that doesn't use any and reloading the page will cause this error. Ember hasn't loaded any helpers, but ember inspector is expecting some.

https://github.com/emberjs/ember-inspector/blob/master/ember_debug/container-debug.js#L73

```
return instancesByType[type].map(...);
```

should check that `instancesByType[type]` exists before `map`'ing

**Comment by erichonkanen** [comment] 2015-03-30 17:38
ran into this issue... how can I resolve?

**Comment by teddyzeenny** [comment] 2015-03-30 19:02
@erichonkanen close and re-open devtools, the error should go away. A permanent fix for this bug is coming soon.

**Comment by erichonkanen** [comment] 2015-03-30 19:10
@teddyzeenny ok awesome thanks!

**Closed** 2015-04-04 12:14 UTC
