### ISSUE TITLE
Doesn't work with Chrome Version 55.0.2883.75 (64-bit, OS X) & ember-cli

### ISSUE THREAD

**Issue by rankam** [emberjs/ember-inspector#621] opened 2016-12-08 22:35 UTC
<img width="1280" alt="screen shot 2016-12-08 at 10 34 07 pm" src="https://cloud.githubusercontent.com/assets/3443458/21030473/8ebf5016-bd96-11e6-8683-19bfa109b8f8.png">

I've also edited chrome://extensions:

<img width="1276" alt="screen shot 2016-12-08 at 10 42 16 pm" src="https://cloud.githubusercontent.com/assets/3443458/21030694/e2b62aa4-bd97-11e6-8c6f-a1c0a9b93c7f.png">

Using ember-cli: 2.10.0 and simply did ember new [project-name]. Any suggestions would be greatly appreciated!

**Comment by locks** [comment] 2016-12-09 09:16
Are you sure you used Ember CLI v2.10.0?

**Comment by rankam** [comment] 2016-12-11 03:20
Yes, absolutely positive.

**Comment by rwjblue** [comment] 2016-12-11 03:40
I am assuming this is the prior iteration of the welcome-page issue (where the welcome page itself wasn't an actual ember app). 

Please provide a demo repo so we can confirm...

**Comment by dmagunov** [comment] 2016-12-22 01:09
I'm also have issue with detecting ember application on latest nwjs builds (with Chrome >= 55)

**Comment by nayan108** [comment] 2017-01-03 19:41
I have the same issue with Ember 2.10 running on Windows 10. Problem on both firefox and chrome extensions.

**Comment by nayan108** [comment] 2017-01-03 19:52
OK. I think I have found the problem. If you simply do: ember new xyz; cd xyz; ember server; then you have the problem above. But if you edit the app by adding a model, route or template (any ember functionality, for that matter), then the inspector works fine. So, the default app that gets built out of the box does not seem to have ember functionality.

**Comment by rwjblue** [comment] 2017-01-03 19:58
Can you please run the following:

    npm ls ember-welcome-page

I suspect you are using 1.x which renders a static HTML page with no JS (and therefore does not work with the inspector). As of ember-welcome-page@2 it is part of a proper Ember app and should work with the inspector just fine.

**Comment by locks** [comment] 2017-01-03 21:01
Ember CLI v2.10 still comes with `ember-welcome-page@1` :\ This will stop being an issue as soon as Ember CLI v2.11 gets released, hopefully next week.

**Comment by locks** [comment] 2017-01-03 21:02
As it is I believe this might be a wontfix, unless some intrepid soul can find a way to minimally update the 1.x branch of `ember-welcome-page` to avoid this problem.

**Comment by atalargo** [comment] 2017-02-07 09:36
I have the same issue (with a real app not the welcome page) but with Vivaldi 1.6.689.40 (a chromium based browser and compatible wit hall Chrome extensions.) The extension works before with it and now, no (since some weeks, may be months) 
Under MacOsX

**Comment by locks** [comment] 2017-02-07 13:26
I'm closing this as Ember CLI v2.11 with the new version of `ember-welcome-page` is out and this issue is resolved for new applications.
@atalargo if you're on 2.10 or lower, you need to create a template as instructed. You can reach us on Slack for further assistance, thanks.

**Closed by locks** 2017-02-07 13:26 UTC

**Comment by dmagunov** [comment] 2017-02-07 14:14
I have this issue not on the ember-welcome-page, with the real app running nwjs (Chromium >= 55 on Macosx

**Comment by locks** [comment] 2017-02-07 14:31
@dmagunov please open a separate issue with a reproduction, since this isn't related to `ember-welcome-page`.
