### ISSUE TITLE
"Ember Inspector has errored." - Failed to execute 'setEndBefore' and 'setStartAfter'

### ISSUE THREAD

**Issue by camoore1979** [emberjs/ember-inspector#462] opened 2015-09-02 17:58 UTC
I am using the Ember Inspector for resolving deprecations as I upgrade my app. I am getting a warning stating, "Ember Inspector has errored. This is likely a bug in the inspector itself." And there are two specific errors:

"Error message: Failed to execute 'setEndBefore' on 'Range': parameter 1 is not of type 'Node'.

"Error message: Failed to execute 'setStartAfter' on 'Range': parameter 1 is not of type 'Node'."

I am running the latest Ember Inspector 1.9.1 on an Ember app using v. 1.10.0, the ember.debug.js file.

Here's a full screenshot of the callstack:
![image](https://cloud.githubusercontent.com/assets/4583280/9639546/9deab596-517a-11e5-99e6-8cf5a5fbf723.png)

**Comment by locks** [comment] 2016-09-22 14:06
Hi, I'm closing this as I believe this issue has since been resolved. If you still encounter this problem please reopen and submit a reproduction!

**Closed by locks** 2016-09-22 14:06 UTC
