### ISSUE TITLE
Not detecting ember application

### ISSUE THREAD

**Issue by engma** [emberjs/ember-inspector#448] opened 2015-08-10 11:31 UTC
I get this error in my console when I try to open the inspector,.

Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 'replace' of undefined
Stack trace: TypeError: Cannot read property 'replace' of undefined
    at Object.func (http://localhost:8080/ts-web-server/editor/preview/scripts/e6c40d2b.components-ember.js:42330:17)
    at Object.Cache.get (http://localhost:8080/ts-web-server/editor/preview/scripts/e6c40d2b.components-ember.js:16902:38)
    at decamelize (http://localhost:8080/ts-web-server/editor/preview/scripts/e6c40d2b.components-ember.js:42372:31)
    at Object.func (http://localhost:8080/ts-web-server/editor/preview/scripts/e6c40d2b.components-ember.js:42297:14)
    at Object.Cache.get (http://localhost:8080/ts-web-server/editor/preview/scripts/e6c40d2b.components-ember.js:16902:38)
    at Object.dasherize (http://localhost:8080/ts-web-server/editor/preview/scripts/e6c40d2b.components-ember.js:42376:37)
    at ember$data$lib$system$normalize$model$name$$normalizeModelName (http://localhost:8080/ts-web-server/editor/preview/scripts/e6c40d2b.components-ember.js:61541:27)
    at ember$data$lib$system$store$$Service.extend.modelFactoryFor (http://localhost:8080/ts-web-server/editor/preview/scripts/e6c40d2b.components-ember.js:69259:37)
    at ember$data$lib$system$store$$Service.extend.modelFor (http://localhost:8080/ts-web-server/editor/preview/scripts/e6c40d2b.components-ember.js:69228:28)
    at ember$data$lib$system$store$$Service.extend.all (http://localhost:8080/ts-web-server/editor/preview/scripts/e6c40d2b.components-ember.js:68831:38)

**Comment by teddyzeenny** [comment] 2015-08-10 11:44
Hello, I need more info.
Your Ember, Ember data versions.
Using ember-cli?
Did you check if the error happens without the Ember Inspector? (Close and reopen devtools to close the Ember Inspector)
This happens the moment you open the Ember Inspector or do you do something first like visit the "Routes" pane?

**Comment by engma** [comment] 2015-08-10 13:40
I am using ember 1.10, ember data 1.0-beta-15.

this happens only when I open the ember inspector, the moment I open it, it shows this error in the console.

This is what happens, 2 scenarios

1- I open my app and when its fully loaded, I open ember inspector, it opens, but I can't open the 'data' tab and the error is thrown at the console.

2- I open my app with ember inspector already open, then it says cannot detect ember app, and the is thrown on start.

**Comment by teddyzeenny** [comment] 2015-08-10 18:17
Looks like the issue is with the data tab. Most likely an issue with getting your list of models. Is your app somewhere online I can access? Can you reproduce this issue in a jsbin or in a public repo?

**Comment by engma** [comment] 2015-08-10 23:50
Well the App is relatively big and may not be able to re produce it and it's for closed use only, but it contains a lot of models, but it was working just fine before in Firefox and in Chrome, apparently it's something in the new version.

But it's a very simple Ember structure, it's some models with some relations in them. I will try to debug it and post exactly when in fails

**Comment by locks** [comment] 2016-09-15 13:36
Hi, I'm closing this as it doesn't look relevant anymore. Feel free to re-open if it's still a problem.

**Closed by locks** 2016-09-15 13:36 UTC
