### ISSUE TITLE
Ember not detected in chrome:// URLs

### ISSUE THREAD

**Issue by nathan-osman** [emberjs/ember-inspector#261] opened 2014-11-13 20:18 UTC
I am building a Firefox add-on that uses Ember. Unfortunately, the inspector doesn't detect Ember in URLs that begin with `chrome://`. It would be terrific if I could debug my add-on with the Ember inspector.

**Comment by jakecraige** [comment] 2015-01-07 22:44
I can't find where this was answered before, but chrome won't allow extensions to access the `chrome://` protocol, so it's not possible. 

Using something like [ember-cli-remote-inspector](https://github.com/joostdevries/ember-cli-remote-inspector) you might be able to get it working

**Comment by dharma-guardian** [comment] 2015-01-08 12:30
Same problem here. Accounts for ```chrome-extension://``` as well.
Thx jakecraige, but I cannot use ```ember serve```, because I need ```chrome.runtime``` as I'm building a chrome extension.

**Comment by nathan-osman** [comment] 2015-01-08 16:17
This bug is for Firefox, however.

**Comment by Noah-Huppert** [comment] 2015-01-08 16:22
Just curious where do `chrome://` urls apear in Firefox?

**Comment by nathan-osman** [comment] 2015-01-08 16:23
Firefox uses the `chrome://` URI scheme to serve content from add-ons.

**Comment by iamolivinius** [comment] 2015-06-16 12:15
Is there any progress on this issue? I'd love to use ember-inspector to debug my chrome extension :<3:

**Comment by nathan-osman** [comment] 2015-06-16 17:09
This bug isn't about Chrome extensions, it's about Firefox add-ons. Please file a separate bug for Chrome.

**Comment by locks** [comment] 2016-09-22 13:53
Closing issue due to staleness. Please reopen if it still applies, and please provide a reproduction!

**Closed by locks** 2016-09-22 13:53 UTC
