### ISSUE TITLE
"Cannot add property toString, object is not extensible"

### ISSUE THREAD

**Issue by richiethomas** [emberjs/ember-inspector#711] opened 2017-08-31 15:46 UTC
When developing on localhost, I click a model instance in the "Data" section of the Ember Inspector, the right-hand window (which normally shows details of that instance) fails to appear.  The window does appear when browsing in other sections of the inspector, such as "Containers".  I'm using Chrome v. Version 60.0.3112.113 (Official Build) (64-bit) on OSX 10.11.6.

Stack Trace:
`TypeError: Cannot add property toString, object is not extensible`
`    at Mixin.classToString [as toString] (http://localhost:4203/assets/vendor.js:53354:21)`
`    at mixins.forEach.mixin (<anonymous>:3029:24)`
`    at Array.forEach (<anonymous>)`
`    at Class.mixinsForObject (<anonymous>:3026:14)`
`    at Class.sendObject (<anonymous>:2942:26)`
`    at Class.inspectModel (<anonymous>:856:37)`
`    at Object.sendEvent (http://localhost:4203/assets/vendor.js:34079:18)`
`    at Class.trigger (http://localhost:4203/assets/vendor.js:50069:19)`
`    at wrap (<anonymous>:3438:14)`
`    at Class.<anonymous> (<anonymous>:3468:18)`

**Comment by metzelhoff** [comment] 2017-08-31 20:27
I'm experiencing the same issue... Only in dev environment. I'm able to open inspector in production with no issues.

**Comment by richiethomas** [comment] 2017-08-31 20:28
Ditto- inspector works as expected on non-localhost domains.

**Comment by metzelhoff** [comment] 2017-08-31 21:28
@richiethomas check out issue #706. There is a fix and will be released within the next day or so.

**Comment by locks** [comment] 2017-08-31 21:58
Duplicate of https://github.com/emberjs/ember-inspector/issues/706, as mentioned above.

**Closed by locks** 2017-08-31 21:58 UTC
