### ISSUE TITLE
Show angle-bracket components

### ISSUE THREAD

**Issue by cjroebuck** [emberjs/ember-inspector#369] opened 2015-05-23 13:32 UTC
Maybe I'm jumping the gun here a little but is the latest version of the inspector supposed to show angle bracket components in the View Tree? If so, they aren't showing up for me. (v1.8.0)

**Comment by teddyzeenny** [comment] 2015-05-24 15:22
Did you check the "components" checkbox in the view tree? It's supposed to be working. Can you reproduce this in a jsbin?

**Comment by teddyzeenny** [comment] 2015-05-24 16:34
Is it possible the component is inside an `{{#each}}`?

**Comment by locks** [comment] 2016-07-28 04:54
Since angle brackets components were only in Ember for one beta version and are currently being revamped, I'm closing this issue.

**Closed by locks** 2016-07-28 04:54 UTC
