### ISSUE TITLE
Counts in data tab not accurate if primary key is not numeric

### ISSUE THREAD

**Issue by typeoneerror** [emberjs/ember-inspector#405] opened 2015-06-21 23:18 UTC
Not sure if this is actually a bug or not, but I am seeing "0" in the tabs when I have a model that has a string for its "id" property (in this case, I am modeling a Google Analytics property...

![screen shot 2015-06-21 at 4 15 03 pm](https://cloud.githubusercontent.com/assets/218700/8273802/227e2bea-1831-11e5-935d-8abf1251b2a2.png)

**Comment by teddyzeenny** [comment] 2015-06-22 12:38
Looks like a bug. I will look into this.

**Comment by Rrrapture** [comment] 2015-06-27 02:03
I'm also getting all empty model types in the Inspector Data tab. No ids or other properties show. 

Ember      : 1.13.2
Ember Data : 1.13.4
jQuery     : 2.1.3

![empty-model-types](https://cloud.githubusercontent.com/assets/514372/8390017/dba05e7e-1c35-11e5-9f3f-82b13127ae22.png)

**Comment by teddyzeenny** [comment] 2015-06-27 12:57
I can't reproduce this issue. Can you please provide a jsbin/repo demonstrating this problem?

**Comment by typeoneerror** [comment] 2015-06-27 17:28
@teddyzeenny yeah, seems to be working for me this morning. Unfortunately doesn't seem reproducible with any reliability. @Rrrapture's seems like a different issue because she's seeing no properties either.

**Comment by teddyzeenny** [comment] 2015-08-05 22:06
Closing as it seems to be working now. @Rrrapture I'm happy to reopen a new issue if you're still having problems.

**Closed by teddyzeenny** 2015-08-05 22:06 UTC
