### ISSUE TITLE
Cannot read property 'dependencies' of undefined

### ISSUE THREAD

**Issue by myartsev** [emberjs/ember-inspector#660] opened 2017-05-05 01:34 UTC
When attempting to inspect the routes for [https://www.linkedin.com/feed/](https://www.linkedin.com/feed/) there is an error in the console and none of the routes are loaded in the inspector.

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 'dependencies' of undefined
Stack trace: TypeError: Cannot read property 'dependencies' of undefined
    at i.loadBundle (https://static.licdn.com/sc/h/br/c6wp1oio8pc4iag9eeyb85i2f:14001:29)
    at i._loadEngineInstance (https://static.licdn.com/sc/h/br/c6wp1oio8pc4iag9eeyb85i2f:18389:57)
    at I.getHandler (https://static.licdn.com/sc/h/br/c6wp1oio8pc4iag9eeyb85i2f:18373:58)
    at i.buildSubTree (<anonymous>:4152:63)
    at i.<anonymous> (<anonymous>:4061:22)
    at u.p.get (https://static.licdn.com/sc/h/br/c6wp1oio8pc4iag9eeyb85i2f:3748:20)
    at Object.a [as get] (https://static.licdn.com/sc/h/br/c6wp1oio8pc4iag9eeyb85i2f:4569:15)
    at i.get (https://static.licdn.com/sc/h/br/c6wp1oio8pc4iag9eeyb85i2f:5806:52)
    at i.sendTree (<anonymous>:4067:28)
    at i.getTree (<anonymous>:4037:14)
```

![ember_inspector_linkedin_routes](https://cloud.githubusercontent.com/assets/4885345/25731112/fe4d475e-3108-11e7-8b01-3b819958d637.png)

**Comment by rwwagner90** [comment] 2018-04-29 14:40
This is a duplicate of #632. We need to get engines support in, before most things on LI will work.

**Closed by rwwagner90** 2018-04-29 14:40 UTC
Labels: duplicate
