### ISSUE TITLE
isGlimmerTwo crashes in tests

### ISSUE THREAD

**Issue by knownasilya** [emberjs/ember-inspector#828] opened 2018-07-09 21:27 UTC
```
VM23467:4684 Uncaught TypeError: Cannot read property 'hasRegistration' of undefined
    at Class.isGlimmerTwo (<anonymous>:4684:41)
    at Class.init (<anonymous>:4494:16)
    at Class.superWrapper [as init] (ember-utils.js:428)
    at new Class (core_object.js:143)
    at Function._ClassMixinProps.create (core_object.js:297)
    at Class.startModule (<anonymous>:2289:29)
    at run (<anonymous>:2318:14)
    at Backburner._run (backburner.js:758)
    at Backburner.run (backburner.js:468)
    at run (ember-metal.js:408)
```

Owner seems to be undefined. Running the inspector in `/tests` url. This happens when I just open the inspector tab. Using:

```
Ember             : 3.1.3
Ember Data        : 3.1.1
jQuery            : 3.3.1
Ember Simple Auth : 1.6.0
Model Fragments   : 3.0.0
```

<img width="711" alt="screen shot 2018-07-09 at 5 29 04 pm" src="https://user-images.githubusercontent.com/34726/42476969-9fca4d4c-839d-11e8-95ca-cf77e3f02c88.png">

**Comment by rwwagner90** [comment] 2018-07-10 01:19
I believe this might be a duplicate of https://github.com/emberjs/ember-inspector/issues/818

**Closed as completed** 2018-07-10 03:26 UTC
Labels: duplicate
