### ISSUE TITLE
Properties of the component can not be inspected due to possible bug.

### ISSUE THREAD

**Issue by mikailcolak** [emberjs/ember-inspector#1827] opened 2021-12-06 17:15 UTC
**Describe the bug**
When I tried to inspect the component properties via clicking the `prop="..."` ellipsis, a warning logged into the console.

**To Reproduce**
1. Go to 'Components tab.'
2. Click on 'Ommited property of the component via ellipsis(...).'
3. Check the built-in console for warnings.

**Expected behavior**
To be able to see the component's properties as before without an error/warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/3528429/144890517-b2943053-b626-4475-b9de-9d6f17adb546.png)
![image](https://user-images.githubusercontent.com/3528429/144891281-cdd9a689-be10-47d7-912d-8f22ebae2546.png)

```
VM44646:91 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: ["__LEGACY_OWNER","__ARGS__","__HAS_BLOCK__","__PROPERTY_DID_CHANGE__"].any is not a function
Stack trace: TypeError: ["__LEGACY_OWNER","__ARGS__","__HAS_BLOCK__","__PROPERTY_DID_CHANGE__"].any is not a function
    at isInternalProperty (<anonymous>:4708:101)
    at addProperties (<anonymous>:4619:11)
    at ownProperties (<anonymous>:4596:12)
    at Class.mixinDetailsForObject (<anonymous>:4384:21)
    at Class.mixinsForObject (<anonymous>:4430:31)
    at Class.sendObject (<anonymous>:4260:26)
    at Class.inspectById (<anonymous>:4168:16)
    at sendEvent (http://localhost:4200/assets/vendor.js:38381:14)
    at Class.trigger (http://localhost:4200/assets/vendor.js:52801:28)
    at <anonymous>:5079:16
```

**Environment**
Ember version: 3.24
Browser: Chrome Version 96.0.4664.55 (Official Build) (x86_64), Firefox Version 94.0.2 (Build ID 20211119140621).

**Comment by mikailcolak** [comment] 2021-12-06 17:20
Most probably related to [replace [].any with [].some #1814](https://github.com/emberjs/ember-inspector/pull/1814)

**Comment by rwwagner90** [comment] 2021-12-07 00:10
Duplicate of #1812

**Closed by rwwagner90** 2021-12-07 00:10 UTC
Labels: bug
