### ISSUE TITLE
ember-infinity seems to break ember inspector

### ISSUE THREAD

**Issue by cwilli34** [emberjs/ember-inspector#580] opened 2016-08-26 18:00 UTC
Getting the following error on the /# Routes tab:

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Could not find module `ember-infinity/mixins/route` imported from `ember-osf/mixins/infinity-custom`
Stack trace: Error: Could not find module `ember-infinity/mixins/route` imported from `ember-osf/mixins/infinity-custom`
```

It will not load any routes information.  

The following is the code, based off of the ember-infinity README.md, and module does exist in the node_modules directory:

```
import Ember from 'ember';
import InfinityRoute from 'ember-infinity/mixins/route';
```
Then: 
`export default Ember.Mixin.create(InfinityRoute, { .....`

I am not sure if this is an error with ember-infinity or Ember Inspector

**Comment by teddyzeenny** [comment] 2016-08-27 10:54
Hi, thanks for reporting this. Your app can't find the module 'ember-infinity/mixins/route'. The inspector is triggering the error probably because it's the first one evaluating this route's code. Try closing the inspector (by closing devtools and reopening) and visiting that route. If you also get an error it's confirmed that this is unrelated to the inspector.

**Comment by cwilli34** [comment] 2016-08-31 18:42
It definitely happens every single time when you click on `/# Routes`.

**Comment by abrinckm** [comment] 2016-10-12 16:46
@cwilli34, Having the same problem. Have you discovered any workarounds?

**Comment by teddyzeenny** [comment] 2016-10-12 16:53
Did you try visiting the route that's importing ember infinity with the inspector closed? I highly doubt this an inspector issue.

**Comment by cwilli34** [comment] 2016-10-13 16:19
Sorry guys.  Forgot to tell you that this is definitely a ember-infinity issue, and if you update to the latest version of ember-infinity the error went away.  At least on my setup.

**Comment by teddyzeenny** [comment] 2016-10-13 17:15
👍

**Closed by teddyzeenny** 2016-10-13 17:15 UTC
