### ISSUE TITLE
Cannot inspect a model in detail

### ISSUE THREAD

**Issue by vanadar** [emberjs/ember-inspector#609] opened 2016-10-11 09:34 UTC
Hello,

If I want to inspect a model (by clicking on an instance of a EmberData model) I have the following error:

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 'toString' of undefined
Stack trace: TypeError: Cannot read property 'toString' of undefined
    at CoreObject.PrototypeMixin._emberMetalMixin.Mixin.create._Mixin$create.toString (http://localhost:4200/assets/vendor.js:53451:37)
    at Object.addListener (http://localhost:4200/assets/vendor.js:34685:88)
    at addObserver (http://localhost:4200/assets/vendor.js:38047:23)
    at Class.bindPropertyToDebugger (<anonymous>:3244:7)
    at <anonymous>:3259:20
    at Array.forEach (native)
    at <anonymous>:3253:26
    at Array.forEach (native)
    at Class.bindProperties (<anonymous>:3252:20)
    at Class.mixinsForObject (<anonymous>:3203:12)
```

I'm using 
Ember 2.8
Ember-data 2.8.0
Ember Inspector 2.0.3

**Comment by teddyzeenny** [comment] 2016-10-11 09:38
Which Ember Data version?

**Comment by vanadar** [comment] 2016-10-11 09:41
the version of Ember-Data is also 2.8.0

**Comment by teddyzeenny** [comment] 2016-10-12 11:57
I'm unable to reproduce this. Can you reproduce it in jsbin, an online app, or a public repo?

**Comment by mpirio** [comment] 2016-11-06 11:59
Hello,

This error appear when we use these models:

```
// model/base.js
import Ember from 'ember';
import Model from 'ember-data/model';

export default Model.extend({
	modelName: Ember.computed.alias('constructor.modelName')
});

// model/model1.js
import Ember from 'ember';
import Base from 'Boondmanager/models/base';

export default Base.extend({
	...
});
```

If we inspect `model1` with Ember Inspector, we have the same error. But if we comment `modelName` CP in `Base` model, no error...

We use this CP to get the `modelName` of a polymorphic relationship (see [How to get the modelname of a polymorphic relationship belongsto](http://discuss.emberjs.com/t/how-to-get-the-modelname-of-a-polymorphic-relationship-belongsto/11422/3) on discuss.emberjs.com) so we can use `{{model.ourRelation.modelName}}` instead of `{{model.ourRelation.content.constructor.modelName}}` in templates.

**Comment by rwwagner90** [comment] 2018-10-14 20:50
@pbishop16 any progress updates on this?

**Comment by pbishop16** [comment] 2018-11-07 20:36
@rwwagner90 I greatly apologize, but no updates. I am finally hitting a solid steady state on my new job. Will address this week.

**Comment by pbishop16** [comment] 2018-12-05 20:42
@rwwagner90 Delayed, but still in progress.

**Comment by rwwagner90** [comment] 2018-12-06 15:14
@pbishop16 please let me know if you need anything from me 👍

**Comment by rwwagner90** [comment] 2019-03-27 20:15
This is out of scope for now. Please use `constructor.modelName` instead.

**Closed by rwwagner90** 2019-03-27 20:15 UTC
Labels: wontfix
