### ISSUE TITLE
In Firefox 61.0.1 masOS - does not work

### ISSUE THREAD

**Issue by belgoros** [emberjs/ember-inspector#831] opened 2018-07-20 08:38 UTC
I added the add-on to Firefox `61.0.1` version on macOS `10.13.3` and the Ember tab is never active (unresponsive) :

<img width="1440" alt="screen shot 2018-07-20 at 10 35 21" src="https://user-images.githubusercontent.com/83579/42992390-aeacbd90-8c08-11e8-971c-c05885b5d93c.png">

As you can see, no matter which tab becomes actif once I click it, but it is not the case for Ember's one

When using the add-on in Chrome, it works as needed:

<img width="1436" alt="screen shot 2018-07-20 at 10 36 52" src="https://user-images.githubusercontent.com/83579/42992457-da4790b0-8c08-11e8-8317-60a225486a48.png">

**Comment by bsylvain** [comment] 2018-07-20 13:40
Same problem with Firefox 61.0.1 on windows 10.  The ember tab in the dev tools is unresponsive.

**Comment by rwwagner90** [comment] 2018-07-20 13:53
Duplicate of https://github.com/emberjs/ember-inspector/issues/819

**Closed by rwwagner90** 2018-07-20 13:53 UTC
