### ISSUE TITLE
No ember application detected until I reload the inspector

### ISSUE THREAD

**Issue by JasonLovrien** [emberjs/ember-inspector#1834] opened 2021-12-12 23:51 UTC
Chrome Version 96.0.4664.93 (Official Build) (x86_64)
Mac Big Sur Version 11.6 (20G165)

After working on a local app for  several weeks, I started getting the "Ember application not detected!" message every time I load the page.
However, if I right click inside the chrome inspector and click "reload frame" the message goes away and my data shows up.
But, when I click to try to expand submenus (like clicking on the ... of an array in a component), I get the following warning in console:

Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: ["__LEGACY_OWNER","__ARGS__","__HAS_BLOCK__","__PROPERTY_DID_CHANGE__"].any is not a function
Stack trace: TypeError: ["__LEGACY_OWNER","__ARGS__","__HAS_BLOCK__","__PROPERTY_DID_CHANGE__"].any is not a function
    at isInternalProperty (<anonymous>:4708:101)
    at addProperties (<anonymous>:4619:11)
    at ownProperties (<anonymous>:4596:12)
    at Class.mixinDetailsForObject (<anonymous>:4384:21)
    at Class.mixinsForObject (<anonymous>:4430:31)
    at Class.sendObject (<anonymous>:4260:26)
    at Class.inspectById (<anonymous>:4168:16)
    at sendEvent (https://localhost:4500/assets/vendor.js:21973:14)
    at Class.trigger (https://localhost:4500/assets/vendor.js:36493:28)
    at <anonymous>:5079:16

**Comment by rwwagner90** [comment] 2021-12-13 17:58
Duplicate of #1812

**Closed by rwwagner90** 2021-12-13 17:58 UTC
