### ISSUE TITLE
Ember-data 3.7 + Pure Class models (properties inspector issue)

### ISSUE THREAD

**Issue by lifeart** [emberjs/ember-inspector#943] opened 2019-02-28 14:36 UTC
given:

```ts
import Model from 'ember-data/model';
import { attr } from '@ember-decorators/data';
import { computed } from '@ember-decorators/object';

export default class User extends Model{
  @attr('string') 
  public firstName !: string;

  @attr('string')
  public lastName !: string;

  @computed('firstName', 'lastName')
  get fullName() {
    return this.lastName + ' ' + this.firstName;
  }
  // normal class body definition here
}

// DO NOT DELETE: this is how TypeScript knows how to look up your models.
declare module 'ember-data/types/registries/model' {
  export default interface ModelRegistry {
    'user': User;
  }
}
```

![image](https://user-images.githubusercontent.com/1360552/53573782-4ec61300-3b7f-11e9-9e2d-1fb018e600fe.png)

![image](https://user-images.githubusercontent.com/1360552/53573801-57b6e480-3b7f-11e9-8345-ee05f58ad1cf.png)

**Comment by lifeart** [comment] 2019-02-28 14:37
where is no `fullName`, `lastName`, `firstName` props

**Comment by rwwagner90** [comment] 2019-08-19 18:08
@lifeart is this still an issue? If so, do you have a deployed app I could reproduce with?

**Comment by rwwagner90** [comment] 2019-08-19 20:50
I think this may have been fixed by https://github.com/emberjs/ember-inspector/pull/1006 if you could please try it out and let me know 😃

**Comment by Windvis** [comment] 2019-08-20 07:18
@rwwagner90 I just tried it by checking out the master branch and running the dev version of Ember Inspector, but it looks like it's not working yet:

![Screenshot 2019-08-20 at 09 15 40](https://user-images.githubusercontent.com/3533236/63325835-38796280-c32b-11e9-98ca-850eb50ea1a2.png)

**Comment by lifeart** [comment] 2019-08-20 09:04
Looks like it's not working for 3.7

![image](https://user-images.githubusercontent.com/1360552/63333668-77ff7900-c342-11e9-9e88-e8de21bf29e9.png)

![image](https://user-images.githubusercontent.com/1360552/63333772-a54c2700-c342-11e9-8c6f-018ea6def9b3.png)

**Comment by Windvis** [comment] 2019-08-20 09:18
Yea, the changes are merged into master, but not released in a new version AFAIK.

**Comment by rwwagner90** [comment] 2019-08-20 11:45
Yes, there is no release yet. Will do a release today. Thanks for testing @Windvis!

**Closed by rwwagner90** 2019-08-20 11:45 UTC
Labels: ember-data, octane
