### ISSUE TITLE
ember inspector sidebar not opening in chrome

### ISSUE THREAD

**Issue by camnicklaus** [emberjs/ember-inspector#852] opened 2018-08-02 21:00 UTC
Just started happening today.
2012 macbook pro 15"
OS: 10.13.4
chrome: Version 67.0.3396.99 (Official Build) (64-bit)

title says it all... the sidebar that shows the model properties doesn't open

screen video trying to see data props... the extension I used to record lost track of the mouse for some reason so it looks like i'm not clicking on the models, but I was ;)

https://drive.google.com/file/d/1NoHr_eWD8SzqtlWgRxeEdF-e3C9RInAN/view

**Comment by rwwagner90** [comment] 2018-08-02 21:06
@camnicklaus is this a duplicate of https://github.com/emberjs/ember-inspector/issues/851?

**Closed** 2018-08-02 21:16 UTC
Labels: duplicate

**Comment by camnicklaus** [comment] 2018-08-02 21:29
@rwwagner90 yeah, I guess it is. I get no errors though.

**Comment by rwwagner90** [comment] 2018-08-03 01:14
It's logged as a warning, not an error.
