### ISSUE TITLE
Can't select the Ember inspector tab in Firefox

### ISSUE THREAD

**Issue by kennydp** [emberjs/ember-inspector#819] opened 2018-06-06 10:08 UTC
I am currently on firefox version 61.0b11 and I can't seem to select the Ember inspector tab. I have tried this with multiple pages that use Ember, but it seems to be a firefox issue. I don't get any error in the console when trying to go to the Ember inspector tab. I currently have version 3.1.3 of the inspector installed.

**Comment by tonyfinn** [comment] 2018-06-07 13:04
```
Error: Unknown event: ["devtools.main", "enter", "webext-devtools-panel-ember-inspector_emberjs_com-1442-0"]
```

I get the following error in the browser console when attempting to open the inspector.

**Comment by rwwagner90** [comment] 2018-06-07 13:15
@teddyzeenny @pbishop16 is that error helpful for your debugging?

**Comment by pbishop16** [comment] 2018-06-08 13:42
@rwwagner90 It's definitely something to work with. I have seen the same error on my end. I will see what I can find.

**Comment by rwwagner90** [comment] 2018-06-28 15:39
@famousfrank yes, this is a known issue, the current version of Ember Inspector just does not work in Firefox. We have been unable to figure out why. @pbishop16 has been trying to talk to Mozilla and find out.

**Comment by jrock2004** [comment] 2018-06-29 15:43
I am on Solus using Firefox 60.0.1 (64-bit) and the addon is working for me

**Comment by rwwagner90** [comment] 2018-07-02 12:12
@jrock2004 what about FF 61?

**Comment by jrock2004** [comment] 2018-07-02 20:05
@rwwagner90 Solus just upgraded me to 61 and now its broken. So it does seem like 61 introduced it

**Comment by rwwagner90** [comment] 2018-07-02 22:13
I don't know of any way to debug this. Would love to find someone with experience with FF that could help!

**Comment by jrock2004** [comment] 2018-07-03 01:02
**When opening debugging**

![image](https://user-images.githubusercontent.com/655716/42193122-e28bb2fa-7e3a-11e8-8ae1-0cc4fa99fca7.png)

Trying to figure how to get break points to hit. But maybe because of this error its not even firing your code yet?

**Comment by jrock2004** [comment] 2018-07-03 03:46
Of course when you go and debug the code that is in master, it works. WTH

**Comment by rwwagner90** [comment] 2018-07-03 13:55
@jrock2004 yes, this is why it has not been fixed. It only errors when deployed, so it's hard for anyone without tribal knowledge of FF to debug.

**Comment by jrock2004** [comment] 2018-07-03 14:02
Well I was thinking that maybe we need to CSP headers to env file but not sure if it would help as I of course cannot deploy

**Comment by rwwagner90** [comment] 2018-07-03 14:09
@jrock2004 if you have anything to try, feel free to submit a PR and we can get @teddyzeenny to deploy and try it out.

**Comment by larryh** [comment] 2018-07-07 19:21
I concur that this started happening in FF 61 (I'm on Ubuntu). Also, nothing in the console for me as well. Sadly, that's all  the information I can give you as I've never done anything with FF internals.

Hopefully a FF guru will be able to figure out what is going on. No error messages leads one to believe that this really could be a bitch to figure out. :-(

**Comment by KwanEsq** [comment] 2018-07-11 22:50
Hello!  I happen to have discovered why this happens, and came across this extension while trying to discover how many are affected.

Basically there is a bug in Firefox that breaks devtools panels for any extension whose ID matches `webconsole|inspector|jsdebugger|styleeditor|netmonitor|storage`

See https://bugzilla.mozilla.org/show_bug.cgi?id=1474379 for the gory details.

Good news: I have a fix, should be in 62.
Bad news: nothing you can do, and unlikely to be fixed in 61 unless some serious issue causes a 61.0.2 release this can ride-along with :frowning_face:.

**Comment by rwwagner90** [comment] 2018-07-12 01:23
@KwanEsq this is awesome news! We were really scratching our heads here.

**Comment by rwwagner90** [comment] 2018-07-12 01:30
@KwanEsq so `ember-inspector` matches even though it just contains `inspector`? Perhaps we should change the id to `ember-dev-tools` or something?

**Comment by jrock2004** [comment] 2018-07-12 03:41
@rwwagner90 I think that is worth a shot

**Comment by KwanEsq** [comment] 2018-07-12 10:15
@rwwagner90 yep, any ID that has any of those strings anywhere, as I eventually discovered after at least half an hour of going crazy trying to figure out why my own prototype with "inspector" in the ID wouldn't open its panel.  (There's some telemetry code that records opening/closing of panels, and tries to limit itself to just specified built-in panels.  Unfortunately it does this by just checking that the panel ID contains one of the above strings, and ext panels' IDs contain a form of their ext ID.  Then it tries to record the data for that panel ID, at which point it errors out because it doesn't recognise the ext panel's ID, hence the error in the second comment.)

Unfortunately while changing the ID will work for using a local build of the ext and developing it, you won't be able to upload/distribute it to any of your existing users.  Once an extension has an ID that's its ID.  You'll essentially be creating a brand new extension if you try to upload to AMO.

**Comment by rwwagner90** [comment] 2018-07-12 10:39
@KwanEsq ah okay, so there is nothing we can do I guess, and we just have to wait for the FF bug to be resolved. Thanks for the info!

**Comment by madnificent** [comment] 2018-07-13 05:50
Can we provide a (manual) workaround for the time being, or are we forced to change our workflow and switch to Chrome/Chromium until the next Firefox release?  I suspect all Firefox users will encounter this problem sometime soon.

**Comment by KwanEsq** [comment] 2018-07-13 12:08
The best workaround will be to (temporarily) switch to Fx Beta or DevEdition once beta8 is out on Tuesday (assuming the patches make it in on time, otherwise beta9 next Friday).

**Comment by larryh** [comment] 2018-07-19 16:40
Thanks for figuring out this head-scratcher, KwanEsq!

**Comment by KwanEsq** [comment] 2018-07-20 15:41
Good news! 62.0b10 is now out with the fix, so you can [download the regular Beta or the DevEdition](https://www.mozilla.org/firefox/channel/desktop/) and use the extension again.

**Comment by KwanEsq** [comment] 2018-07-20 15:49
For future reference, best thing to do in this situation is [get a bug on file](https://bugzilla.mozilla.org/enter_bug.cgi?product=WebExtensions&component=Untriaged) so it's likely to get attention from Fx devs (make use of the regression keyword, and possibly tracking flags).  Bonus points if you can use [mozregression](https://mozilla.github.io/mozregression/) (GUI and CLI versions available!) to find out which bug introduced it, otherwise add the regressionwindow-wanted keyword and someone else should take care of it.

**Comment by yohanmishkin** [comment] 2018-07-20 17:39
@KwanEsq It works!! 10,000 points awarded. THANK YOU!

**Comment by rwwagner90** [comment] 2018-07-23 11:36
Thanks guys! Closing this now, since there is a beta of FF out with the fix.

**Closed by rwwagner90** 2018-07-23 11:36 UTC

**Comment by KwanEsq** [comment] 2018-08-08 20:44
More good news!  There has been a 61.0.2 release, and this was able to ride-along with, so Ember Inspector is now usable in release/61 again, rather than waiting for 62 (currently scheduled for 5th September).
