### ISSUE TITLE
Inspector "Data" tab crashes after update from ED beta.18 to beta.19.1

### ISSUE THREAD

**Issue by mphasize** [emberjs/ember-inspector#391] opened 2015-06-12 11:17 UTC
I'm working on an Ember App with a lot of complex models and relationships. After upgrading from Ember Data beta.18 to beta.19.1 the inspector crashes when I am trying to inspect the details of a record.

Ember Data tab still opens.
Record List shows (overview on the left side, and all records for a model).
When clicking a single record, nothing happens in the UI, and the console says...

```
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: value.hasOwnProperty is not a function
Stack trace: TypeError: value.hasOwnProperty is not a function
    at inspect (<anonymous>:1962:19)
    at inspectValue (<anonymous>:1924:56)
    at <anonymous>:2449:28
    at Array.forEach (native)
    at <anonymous>:2440:24
    at Array.forEach (native)
    at calculateCPs (<anonymous>:2439:18)
    at EmberObject.extend.mixinsForObject (<anonymous>:2249:7)
    at EmberObject.extend.sendObject (<anonymous>:2136:26)
    at Ember.Object.extend.messages.inspectModel (<anonymous>:808:37)
```

**Comment by teddyzeenny** [comment] 2015-06-12 11:19
Duplicate of https://github.com/emberjs/ember-inspector/issues/390

**Comment by mphasize** [comment] 2015-06-12 11:20
Oups, sorry!

**Closed by teddyzeenny** 2015-06-12 11:19 UTC

**Comment by teddyzeenny** [comment] 2015-06-12 11:23
No worries. Fix will be published tomorrow.
