### ISSUE TITLE
Add support to Firefox Nightly: 55.0a1 (2017-05-31) (64-bit)

### ISSUE THREAD

**Issue by wellington1993** [emberjs/ember-inspector#665] opened 2017-06-01 12:17 UTC
Hi,

please add support to Firefox Nightly 55.0a1 (2017-05-31) (64-bit) and add to multiprocess (Like another issue)

Thanks!

**Comment by locks** [comment] 2017-06-02 08:33
Duplicate of https://github.com/emberjs/ember-inspector/issues/666 and https://github.com/emberjs/ember-inspector/issues/661

**Closed by locks** 2017-06-02 08:33 UTC
