### ISSUE TITLE
New iframe implementation not picking up iframe after it's added to the dom

### ISSUE THREAD

**Issue by mansona** [emberjs/ember-inspector#200] opened 2014-08-20 17:08 UTC
Just posting a new issue from my comments on https://github.com/emberjs/ember-inspector/pull/182 

We use ember from within an iframe, and you can see an example on our homepage https://bloo.ie after you click the "ask a question" tab in the bottom left it will open a chat window, which is an ember application in an iframe. You know you've made it to the ember app once it looks like this: 

https://cloudup.com/imQN-P6X5nA

as you can also see from the screenshot the ember application hasn't been identified. I've double checked that i've got the 1.4 version of the chrome app https://cloudup.com/c4ZwxA67037 

If there is anything you want me to do to test this out or debug it let  me know and i'd be happy to help

**Comment by raido** [comment] 2015-05-25 09:21
This should be fixed, really that // FIXME in the code.

I have use case of versioned app inside an ember app.

My whole app has been built into two separate apps.

1) Is a login app, which handles account login, signup etc. and provides public API to the app running in the container (iframe).
2) Is the actual app version that has been set for the account.

This means i have an ember app, that includes another ember app in iframe after sign in. Currently the app in the iframe is rarely picked up, but when it does it works just fine with the inspector. The 500ms delay in the code, is too short for my use case, because authentication and loading the app into iframe container takes longer, which means my iframe ember app is not having an URL yet and thus the URL is not sent to the inspector.

**Comment by raido** [comment] 2015-06-12 20:07
Any news?

**Comment by teddyzeenny** [comment] 2015-06-13 19:32
@raido sorry for the late reply. I'm not sure how to fix this yet off the top of my head (or if it is fixable). Will need to think about it/research more. I'm honestly focused on other issues right now. If you'd like to work on this I'm happy to guide you in any way I can.

**Comment by raido** [comment] 2015-06-14 12:07
@teddyzeenny I'll look into this in next few weeks, sorry for not being able to give more precise time frame.

**Comment by raido** [comment] 2015-06-15 20:14
I did set up the Inspector from the repo, deploying for development was easy.

I have investigated the issue a bit, i've tried setting the current //FIXME setTimeout longer, hardcoded the URL's for my app in iframe, nothing it does not pick it up.

**Comment by wycats** [comment] 2016-03-17 18:19
Can we use mutation observers to detect new iframes?

**Comment by mansona** [comment] 2017-02-18 15:03
Hi folks, we don't have any need for this anymore so I would like to close this issue. Seeing as it has had quite some discussion I thought I would ask first.

All happy for me to close this?

**Comment by raido** [comment] 2017-02-19 11:55
Yes.

**Closed** 2017-07-06 00:43 UTC

**Comment by gabrielgrant** [comment] 2018-01-13 02:14
This issue seems to be preventing the inspector from working with Ember-Twiddle (see: ember-cli/ember-twiddle#49)... Any chance of re-opening it?

**Comment by jbescoyez** [comment] 2018-09-11 09:56
I'm having the same issue. I'm currently developing a Chrome extension that runs an Ember app in an iframe. I'm unable to inspect it since it is added after the DOM is loaded.

It is easy to reproduce:
* Go to https://ember-twiddle.com/
* Try inspecting the "output" iframe

At the moment, the iframe does not appear in the dropdown.

cc/ @teddyzeenny @mansona @gabrielgrant

**Comment by mansona** [comment] 2018-09-11 10:51
This is potentially an overlap between @Gaurav0 and @rwwagner90 that might be able to shed some light on the situation 😂 

I would recommend that this should at the very least be a new issue @jbescoyez because my original problem was solved 😄 Could you make a new issue?

**Comment by mansona** [comment] 2018-09-11 10:54
For reference, it seems like they are tracking this on the twiddle side here: https://github.com/ember-cli/ember-twiddle/issues/49

**Comment by jbescoyez** [comment] 2018-09-11 12:33
@mansona Done https://github.com/emberjs/ember-inspector/issues/868 :)
