### ISSUE TITLE
EmberInspector breaks with an empty project

### ISSUE THREAD

**Issue by gvelesandro** [emberjs/ember-inspector#606] opened 2016-09-30 01:37 UTC
Repro:
1) Install Ember Inspector
2) create `ember new project`
3) Run `ember s`
4) Open the app in a browser,
5) Navigate to Inspector | Ember Inspector
6) Notice that the inspector is not responsive

**Comment by locks** [comment] 2016-09-30 03:53
Thank you for reporting, duplicate of https://github.com/emberjs/ember-inspector/issues/584. We are currently fixing ember-welcome-page so this doesn't happen!

**Closed by locks** 2016-09-30 03:53 UTC
