### ISSUE TITLE
embr inspector is not working in chrome. ember application not found is cuming.

### ISSUE THREAD

**Issue by reshmaresh02** [emberjs/ember-inspector#2110] opened 2022-08-19 08:39 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
Ember version, browser, etc.

**Additional context**

**Comment by kprasadpvv** [comment] 2022-08-19 16:44
Duplicate of https://github.com/emberjs/ember-inspector/issues/2107

Find the mitigation steps here.
https://github.com/emberjs/ember-inspector/issues/2107#issuecomment-1220695725

**Closed** 2022-08-19 17:00 UTC
Labels: duplicate
