### ISSUE TITLE
Ember inspector is not compatiable with chrome dark mode

### ISSUE THREAD

**Issue by abdullah2891** [emberjs/ember-inspector#699] opened 2017-08-08 13:24 UTC
The options are getting lost in dark mode. I can't use Ember inspector with dark mode on
![image](https://user-images.githubusercontent.com/6827586/29073851-2bf9e2e0-7c1b-11e7-9ea6-87d81cffbdcc.png)

![image](https://user-images.githubusercontent.com/6827586/29073815-0c9e59f8-7c1b-11e7-9c51-aa88c3b25e94.png)

Version
Chrome : Version 59.0.3071.115 
Ember Inspector 1.10.0
Ember 2.3.2
Ember Data 2.14.6
jQuery 2.1.4

**Comment by locks** [comment] 2017-08-15 11:32
Duplicate of https://github.com/emberjs/ember-inspector/issues/524, please refer to that issue.

**Closed by locks** 2017-08-15 11:32 UTC
