### ISSUE TITLE
Feature idea: Allow addons to extend ember inspector

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember-inspector#363] opened 2015-05-17 14:14 UTC
I had an idea that I don't know if it was discussed before (I don't even know if it's technically possible).

The ideas is to allow addons to add extend the functionalities to the ember-inspector. By example, liquidfire providing an extension that adds a new tab to visualize and edit the transitions in the app.

Is possible to have communication between the code of an app and the addons?

**Comment by cibernox** [comment] 2015-05-18 11:55
@teddyzeenny I'd love to have your mind to determine if this is doable. The more I thing about the idea the more advantages I see on it.

By example, if the ember-inspector provides the smallest structure possible and everything else is plugged as an engine (we're not there yet on this topic AFAIK) the burden of supporting several versions of ember would go away. Each version of ember comes with it's own taylor-made inspector engine that it's plugged, the burden of being backwards compatible disappears. 

Maybe the engine should not be in ember itself but in a separate addon, so it can be bugfixed independently, locking the mayor version to the addon to the version of ember, `ember-2.1.0` -> `ember-view-tree-inspector-2.1.0.0` and `ember-routes-inspector-2.1.0.0`.

I'd love to condense this in an RFC if seems reasonable.

**Comment by teddyzeenny** [comment] 2015-05-19 09:14
@cibernox I'm generally with the idea, but unsure about feasibility at the moment. I think it is a similar discussion to https://github.com/emberjs/ember-inspector/issues/321. See [my thoughts](https://github.com/emberjs/ember-inspector/issues/321#issuecomment-89639132) on the matter.

**Comment by cibernox** [comment] 2015-05-19 09:20
I'll try to investigate with something simpler, like the inspector rendering a component that it's not inside it's code but in the code of the application.

**Comment by locks** [comment] 2016-07-28 04:53
Duplicate of #321 as mentioned.

**Closed by locks** 2016-07-28 04:53 UTC
