### ISSUE TITLE
App Switcher breaks inspector

### ISSUE THREAD

**Issue by nummi** [emberjs/ember-inspector#1039] opened 2019-09-25 06:48 UTC
<img width="194" alt="image" src="https://user-images.githubusercontent.com/3692/65575918-c1387f00-df25-11e9-96ef-4064e5de58b9.png">

`Error in event handler: Error: Assertion Failed: You attempted to remove a function listener which did not exist on the instance, which means you may have attempted to remove it before it was added.`

The entire Inspector turns into a white screen.

Seems to be coming from this line: https://github.com/emberjs/ember-inspector/blob/master/app/routes/app-detected.js#L52

I believe updating to 3.11 is the culprit. This PR causes the error:
https://github.com/emberjs/ember-inspector/pull/1000

**Comment by chancancode** [comment] 2019-12-18 21:01
I think this may be fixed in https://github.com/emberjs/ember-inspector/pull/1103/files, @nummi any chance you can re-test? (no rush)

**Comment by nummi** [comment] 2019-12-19 00:05
@chancancode, it's getting better: no empty white screen. Unfortunately Inspector doesn't switch apps and now I'm getting this error:

```
VM129:9027 Uncaught TypeError: Cannot read property '__deprecatedInstance__' of undefined
    at <anonymous>:9027:46
    at <anonymous>:138:9
    at Array.forEach (<anonymous>)
    at Class._messageReceived (<anonymous>:137:30)
    at <anonymous>:378:16
    at Backburner._run (backburner.js:1010)
    at Backburner.run (backburner.js:751)
    at run (index.js:122)
    at MessagePort.<anonymous> (<anonymous>:377:9)
```

**Comment by chancancode** [comment] 2019-12-19 00:20
Thanks! I’ll take a look!

**Comment by rwwagner90** [comment] 2019-12-19 21:15
@chancancode is this still an issue?

**Comment by chancancode** [comment] 2019-12-19 21:44
Yes

**Comment by chancancode** [comment] 2019-12-19 21:46
I haven’t had a chance to look into how it’s supposed to work with iframes yet, but it doesn’t work properly. It may be the case that switching between two apps on the same page and on the same frame works but switching between iframes doesn’t.

**Comment by rwwagner90** [comment] 2019-12-20 01:59
@chancancode was changing the app picker a requirement of the new render node stuff? If not, maybe we can change it back?

**Comment by chancancode** [comment] 2019-12-20 02:15
It was already broken before my change. This issue predated my changes. My change made it crash less badly, but it still doesn’t work.

**Comment by rwwagner90** [comment] 2019-12-20 13:27
@chancancode are you sure? It worked the last time @nummi and I tried it, but we don't try it often.

**Comment by chancancode** [comment] 2019-12-20 16:47
The issue is from September and the description mentioned:

> I believe updating to 3.11 is the culprit. This PR causes the error:
> #1000

But yes I also confirmed it locally. I can try to figure this out but probably have a few other things to look into before getting to this. I also find that the inspector's detection of apps on the current page could be pretty spotty and timing dependent, so probably going to try and fix that as well.

**Comment by rwwagner90** [comment] 2019-12-20 17:21
@chancancode sorry, you are correct, it's been a long couple of weeks 😅

**Comment by chancancode** [comment] 2019-12-20 17:22
No problem! Same 😄

**Comment by patricklx** [comment] 2022-10-04 07:59
should be fixed by https://github.com/emberjs/ember-inspector/pull/2157

**Closed** 2022-10-04 12:57 UTC
Labels: bug
