### ISSUE TITLE
Opera version?

### ISSUE THREAD

**Issue by mathiasbynens** [emberjs/ember-inspector#265] opened 2014-11-27 12:06 UTC
Any chance you’d be willing to upload this to https://addons.opera.com/en/developer/upload/, so that Opera users can enjoy this extension too?

You probably don’t even have to change the code.

**Comment by gnapse** [comment] 2015-01-27 12:42
+1

**Comment by acorncom** [comment] 2016-04-18 15:38
Duplicate of #119 , let's close this one ...

**Closed** 2016-04-18 15:44 UTC
