### ISSUE TITLE
'Cannot add property toString, object is not extensible'

### ISSUE THREAD

**Issue by noxmwalsh** [emberjs/ember-inspector#706] opened 2017-08-23 20:30 UTC
Hey all,

Our team has recently ran into this Ember Inspector related error with the latest 2.1.0 release that went out a few hours ago.  The quickest way to see this is to inspect any Ember model in the data store view.  Has anyone else experienced this?

```javascript
Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot add property toString, object is not extensible
Stack trace: TypeError: Cannot add property toString, object is not extensible
    at Mixin.classToString [as toString] (http://localhost:5000/assets/vendor.js:58602:21)
    at mixins.forEach.mixin (<anonymous>:3029:24)
    at Array.forEach (<anonymous>)
    at Class.mixinsForObject (<anonymous>:3026:14)
    at Class.sendObject (<anonymous>:2942:26)
    at Class.inspectModel (<anonymous>:856:37)
    at Object.sendEvent (http://localhost:5000/assets/vendor.js:39028:18)
    at Class.trigger (http://localhost:5000/assets/vendor.js:55337:25)
    at wrap (<anonymous>:3438:14)
    at Class.<anonymous> (<anonymous>:3468:18)
```

The last part of that stack traces stops here:

```javascript
function classToString() {
    if (!searchDisabled && !this[_emberMetalMixin.NAME_KEY]) {
      processAllNamespaces();
    }

    var ret = undefined;

    if (this[_emberMetalMixin.NAME_KEY]) {
      ret = this[_emberMetalMixin.NAME_KEY];
    } else if (this._toString) {
      ret = this._toString;
    } else {
      var str = superClassString(this);
      if (str) {
        ret = '(subclass of ' + str + ')';
      } else {
        ret = '(unknown mixin)';
      }
      this.toString = makeToString(ret);
    }

    return ret;
  }
```

at 'this.toString = makeToString(ret);' (ret being '(unknown mixin)')

We're using the following library versions:

Ember Inspector | 2.1.0
Ember | 2.8.1
Ember Data | 2.8.1
jQuery | 2.1.4

Thanks in advance!

**Comment by charliemitchell** [comment] 2017-08-23 22:31
I am also encountering the same issue, along with a co-worker.

Chrome Version 60.0.3112.101 (Official Build) (64-bit)
Ember Inspector | 2.1.0
Ember | 2.8.3
jQuery | 3.2.1

**Comment by esse** [comment] 2017-08-24 11:22
Same here.

Chrome Version: 60.0.3112.101 (Official Build) (64-bit)
Ember Inspector: 2.1.0
Ember: 2.8.3

**Comment by campbecf** [comment] 2017-08-24 14:32
Same.

Chrome Version: 60.0.3112.101 (Official Build) (64-bit)
Ember Inspector: 2.1.0
Ember: 2.8.3
Ember Data: 2.4.3

**Comment by campbecf** [comment] 2017-08-24 14:37
Oddly enough this only happens when using the inspector on a locally running ember project. Our released projects on staging / production do not have this issue.

**Comment by rwjblue** [comment] 2017-08-24 14:56
The issue is due to `Mixin.create` using `Object.seal` to seal the mixin that is created. This only happens in debug builds (so in production there will be no errors). 

All of the reports here seem to be coming from users of Ember 2.8, is anyone getting this error on newer Ember versions?

**Comment by aarkus7** [comment] 2017-08-24 16:29
Getting it on Ember 2.10

**Comment by mapohjola** [comment] 2017-08-25 04:54
Also having this problem on Ember 2.10

**Comment by teddyzeenny** [comment] 2017-08-26 12:17
This is an Ember.js core bug for versions < Ember 2.11. In short, calling `toString` on a mixin also attempts to mutate that mixin by overwriting the `toString` method. In debug mode, Ember.js seals the `Mixin` instance by calling `Object.seal`, which prevents non-own properties from being added/changed.

This bug was fixed by [this commit](https://github.com/emberjs/ember.js/commit/f8f259a2e3c1d1c67207acd4027669185287c1db) which is included starting Ember >= 2.11. After this commit, `toString` only mutates the `[NAME_KEY]` property which is already an "own property", therefore the operation is allowed on sealed objects.

The solution seems to be to simply stop calling `toString` on Mixins for Ember < 2.11.

cc @rwjblue

**Closed** 2017-08-26 14:03 UTC

**Comment by Leooo** [comment] 2017-08-29 17:38
@teddyzeenny can you release a new version for this fix please? Many thanks!

**Comment by teddyzeenny** [comment] 2017-08-30 11:08
@Leooo yes I will try to release either today or tomorrow.

**Comment by metzelhoff** [comment] 2017-08-31 21:26
Thank you for this fix! Looking forward to the release

**Comment by Leooo** [comment] 2017-09-02 10:15
@teddyzeenny any update please?

**Comment by teddyzeenny** [comment] 2017-09-02 12:19
The new version is out, let me know if you still have any issues.

**Comment by Leooo** [comment] 2017-09-02 12:32
@teddyzeenny thanks, updated to 2.1.1, but now Ember Inspector does not open at all, having this error message:

Uncaught TypeError: Cannot read property 'impl' of undefined
    at getPrivateImpl (extensions::utils:130:30)
    at Event.publicClassPrototype.(anonymous function) [as addListener] (extensions::utils:148:20)
    at listenToEmberDebugPort (chrome-extension://bmdblncegkenkacieihfhpjfppoconhi/content-script.js:47:32)
    at chrome-extension://bmdblncegkenkacieihfhpjfppoconhi/content-script.js:30:7

**Comment by teddyzeenny** [comment] 2017-09-02 12:36
@Leooo I don't recognize the error, seems like an internal Chrome error. Can you try restarting devtools or Chrome?

**Comment by Leooo** [comment] 2017-09-02 12:37
@teddyzeenny restarting chrome a second time fixed the issue. All good now thanks!
