### ISSUE TITLE
How to read excel file in emberjs and electron

### ISSUE THREAD

**Issue by rajeevr008** [emberjs/ember-inspector#649] opened 2017-04-10 01:53 UTC
I am making a desktop app using emberember.js and electronelectron. I need to read data from excel file- How to read excel file in emberjs. I've no clue about it, really appreciate if you can help

**Comment by locks** [comment] 2017-04-10 10:25
Duplicate of https://github.com/emberjs/ember-inspector/issues/650.

**Closed by locks** 2017-04-10 10:25 UTC
