### ISSUE TITLE
Inspector blank screen 

### ISSUE THREAD

**Issue by eliezertor** [emberjs/ember-inspector#1805] opened 2021-11-19 02:28 UTC
**Describe the bug**
Inspector is completely blank 

**To Reproduce**
1. Go to 'Just open chrome and trying inspecting'

**Expected behavior**
See the ember inspector

**Screenshots**
![Screen Shot 2021-11-18 at 9 18 15 PM](https://user-images.githubusercontent.com/44241785/142554169-0c3c54b8-1d2d-412f-9c96-09ca66a4f0ec.png)

**Environment**
Ember version, browser, etc.
`Chrome Version 95.0.4638.69 (Official Build) (arm64)`
`Ember Inspector V 4.5.2`
`Apple M1`
`macOS Monterey 12.0.1`

**Comment by rwwagner90** [comment] 2021-11-19 14:57
Duplicate of #1797

**Closed by rwwagner90** 2021-11-19 14:57 UTC
Labels: bug
